### ISSUE TITLE
typedef struct in C

### ISSUE THREAD

**Issue by annehutter** [swincas/cookies-n-code#13]
I was wondering what is the difference and implications between the following two cases?

```C
typedef struct foo{
    int x;
} foo;
```
and
```C
typedef struct {
    int x;
} foo;
```

Is the first one just needed for linked lists?

(@manodeep edited for syntax highlighting)

**Comment by manodeep** [comment]
I think both the first and second refer (mostly) to the same thing.
```C
struct foo{
    int x;
};
typedef struct foo foo;
```
This lets you say
```C
foo newvar;
```

instead of 
```C
struct foo newvar;
```

I think in the second case there is no declaring `struct foo something` because the `struct` itself was anonymous. But not totally sure; feel free to play around in [godbolt](https://gcc.godbolt.org/)

**Comment by annehutter** [comment]
Just to clarify both methods allow this declaration
``foo newvar;``
However, if working with linked lists, only the first option works:
``typedef struct foo{
int x;
foo *next:
} foo;``

I think I don't really understand the concept of namespace (as I understand 'foo' before the brackets) when there is a typespace ('foo' after brackets) defined?

**Comment by manodeep** [comment]
Ahh I see what you mean. Yes you do need a forward declaration 
```C
typedef struct foo foo;
struct foo{
    int x;
    foo *foo;
};
```

**Comment by manodeep** [comment]
Here's the relevant [StackOverflow page](https://stackoverflow.com/questions/33131983/structure-pointer-forward-declaration)

Is this okay to close?

**Comment by manodeep** [comment]
@annehutter I think this issue is resolved; I am closing for now -- please feel free to re-open.
