### ISSUE TITLE
Need help setting up Travis CI, documentation hosting and Appveyor for package (e13Tools)

### ISSUE THREAD

**Issue by 1313e** [swincas/cookies-n-code#4]
Title says it all, basically.
I have my own package called e13Tools, and I would like to add some features to add like Travis CI and documentation hosting. I am having trouble doing so, so I would like some help with that if possible.

**Comment by manodeep** [comment]
@1313e I know you have sorted out the CI testing, so closing this issue. Please feel free to post on this issue what you did to get Travis up and working, and what road-blocks you encountered.

**Comment by 1313e** [comment]
@manodeep Want me to give an item during Cookies 'n Code on it at some point?
I am doing basically everything at the moment for PRISM: Travis, AppVeyor, CircleCI, ReadTheDocs, CoverAlls.
