### ISSUE TITLE
help with remote vscode

### ISSUE THREAD

**Issue by manodeep** [swincas/cookies-n-code#60]
I had finally gotten my VSCode working remotely on ozstar where my loaded python environment was being detected (so I had the linter working, and potentially the debugger)

But I ran into the quota limit on `home` directory, so I deleted the `.vscode` directory (it was `~ 800MB!`), based on the internet's advice that the directory would be re-created. The directory has indeed been re-created but now I do not have *any* python being detected :'( 

@olivercoad Help?

**Comment by olivercoad** [comment]
The `~/.vscode` directory contains all the extensions. Deleting it may have uninstalled them, so make sure have have the python extension installed on ozstar.

You could also try setting `python.pythonPath`.

Please paste the python extension output logs.

**Comment by manodeep** [comment]
Thanks! Yup - I had to reinstall the Microsoft python extension, and then a couple of other ones and I seem to be back on track. 

VSCode is still picking up the default system python (2.7.5) but at least I can click on the python on the bottom bar and change it to the module level python (3.6.4)

**Comment by olivercoad** [comment]
Good to hear you're back on track.
You can set it as default so that you don't have to click the bar every time.

Have you got the debugger working?

Before you close the issue, it would be nice if you describe how you solved it to help other people not run into the same quota issue.

**Comment by manodeep** [comment]
I was going to ask you that! Is it possible to have a step-by-step guide to installing + running VSCode on `ozstar`, especially with any specific python modules loaded appropriately?

**Comment by olivercoad** [comment]
Well I don't even use ozstar. I could do a general guide on using the VSCode remote ssh extension but there are plenty of those already. @abatten might be better to ask.

**Comment by manodeep** [comment]
This is all sorted :)
